// frontend/src/pages/Login.vue
<template>
  <div class="flex flex-col items-center justify-center min-h-[70vh]">
    <div class="w-full max-w-md bg-white rounded-2xl shadow-xl p-8 border border-gray-100">
      <h2 class="text-3xl font-extrabold text-gray-900 text-center mb-8">Welcome</h2>
      <form @submit.prevent="handleSubmit" class="space-y-6">
        <div class="flex items-center justify-center space-x-4 mb-4">
          <button type="button" @click="isRegistering = false" :class="['px-4 py-2 text-sm font-medium rounded-md', !isRegistering ? 'bg-indigo-100 text-indigo-700' : 'text-gray-500 hover:bg-gray-50']">Login</button>
          <button type="button" @click="isRegistering = true" :class="['px-4 py-2 text-sm font-medium rounded-md', isRegistering ? 'bg-indigo-100 text-indigo-700' : 'text-gray-500 hover:bg-gray-50']">Register</button>
        </div>

        <div v-if="isRegistering">
          <label for="name" class="block text-sm font-medium text-gray-700">Name</label>
          <input id="name" v-model="name" type="text" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm p-3 border" placeholder="John Doe" />
        </div>
        <div>
          <label for="email" class="block text-sm font-medium text-gray-700">Email Address</label>
          <input id="email" v-model="email" type="email" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm p-3 border" placeholder="you@example.com" />
        </div>
        <div>
          <label for="password" class="block text-sm font-medium text-gray-700">Password</label>
          <input id="password" v-model="password" type="password" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm p-3 border" placeholder="••••••••" />
        </div>

        <button type="submit" :disabled="loading" class="w-full flex justify-center py-3 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 transition-colors disabled:opacity-50">
          {{ loading ? 'Processing...' : (isRegistering ? 'Register' : 'Login') }}
        </button>
        <p v-if="error" class="mt-2 text-center text-sm text-red-600">{{ error }}</p>
      </form>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '../stores/auth'
import { account, ID } from '../services/appwrite'

const router = useRouter()
const authStore = useAuthStore()

const isRegistering = ref(false)
const name = ref('')
const email = ref('')
const password = ref('')
const error = ref('')
const loading = ref(false)

const handleSubmit = async () => {
  error.value = ''

  // JS-level validation (cannot rely on HTML5 required alone)
  if (!email.value.trim()) {
    error.value = 'Email address is required.'
    return
  }
  if (!password.value || password.value.length < 8) {
    error.value = 'Password must be at least 8 characters.'
    return
  }
  if (isRegistering.value && !name.value.trim()) {
    error.value = 'Name is required.'
    return
  }

  loading.value = true
  try {
    if (isRegistering.value) {
      try {
        await account.create(ID.unique(), email.value.trim(), password.value, name.value.trim())
      } catch (e: any) {
        if (e.code === 409) {
          // User already exists — proceed to login
          console.log('User already exists, attempting login')
        } else {
          throw e
        }
      }
    }

    // Clean any existing session before creating new one
    try {
      await account.deleteSession('current')
    } catch (_) {
      // No active session — safe to ignore
    }

    await account.createEmailPasswordSession(email.value.trim(), password.value)
    await authStore.checkAuth()
    router.push('/')
  } catch (err: any) {
    error.value = err.message || 'Authentication failed. Please try again.'
  } finally {
    loading.value = false
  }
}
</script>

// frontend/src/pages/Login.tsx
import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { authApi } from '@/services/api'
import { useAuthStore } from '@/stores/auth'

export default function Login() {
  const navigate = useNavigate()
  const setAuth = useAuthStore((s) => s.setAuth)
  const [phone, setPhone] = useState('')
  const [password, setPassword] = useState('')
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(false)

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault()
    setError('')
    setLoading(true)
    try {
      const res = await authApi.login({ phone, password })
      setAuth(res.token, res.user)
      navigate('/home', { replace: true })
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Login failed')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-indigo-950 to-indigo-700 px-5 py-10">
      <div className="mb-6 flex flex-col items-center text-center text-white">
        <span className="text-5xl">🏘️</span>
        <h1 className="mt-3 text-2xl font-extrabold tracking-wide">NEXTDOOR</h1>
        <p className="mt-1 text-sm text-indigo-200">Welcome back to your neighborhood</p>
      </div>

      <form onSubmit={handleSubmit} className="w-full max-w-sm space-y-4 rounded-2xl bg-white p-6 shadow-xl">
        <div>
          <label className="mb-1 block text-sm font-semibold text-slate-700" htmlFor="phone">
            Phone Number
          </label>
          <input
            id="phone"
            type="tel"
            required
            inputMode="numeric"
            className="input"
            placeholder="e.g. 9999999999"
            value={phone}
            onChange={(e) => setPhone(e.target.value.replace(/\D/g, '').slice(0, 10))}
          />
        </div>
        <div>
          <label className="mb-1 block text-sm font-semibold text-slate-700" htmlFor="password">
            Password
          </label>
          <input
            id="password"
            type="password"
            required
            className="input"
            placeholder="••••••••"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
          />
        </div>

        {error && (
          <p className="rounded-lg bg-red-50 px-3 py-2 text-sm font-medium text-red-600" role="alert">
            {error}
          </p>
        )}

        <button type="submit" disabled={loading} className="btn-primary w-full">
          {loading ? 'Signing in…' : 'Sign In'}
        </button>

        <p className="text-center text-xs text-slate-500">
          Demo — admin <span className="font-semibold">9999999999 / Admin@1234</span>
        </p>
      </form>

      <p className="mt-6 text-sm text-indigo-200">
        New here?{' '}
        <Link to="/register" className="font-semibold text-accent">
          Create an account
        </Link>
      </p>
    </div>
  )
}
