// frontend/src/pages/Profile.vue
<template>
  <div class="space-y-6">
    <div class="bg-indigo-600 rounded-xl p-6 text-white shadow-md">
      <h2 class="text-2xl font-bold">Profile & Settings</h2>
      <p class="text-indigo-100 mt-1">Manage your account</p>
    </div>

    <div class="bg-white rounded-xl shadow-sm border border-gray-100 p-6">
      <div class="flex items-center space-x-4 mb-6">
        <div class="h-16 w-16 rounded-full bg-indigo-100 flex items-center justify-center text-indigo-800 text-xl font-bold">
          {{ authStore.user?.name ? authStore.user.name[0].toUpperCase() : '?' }}
        </div>
        <div>
          <h3 class="text-lg font-bold text-gray-900">{{ authStore.user?.name || 'Loading...' }}</h3>
          <p class="text-sm text-gray-500">{{ authStore.user?.email || '' }}</p>
        </div>
      </div>

      <div class="space-y-4 border-t border-gray-100 pt-6">
        <div class="flex justify-between items-center">
          <div>
            <h4 class="text-sm font-medium text-gray-900">Account Status</h4>
            <p class="text-xs text-gray-500">Active and verified</p>
          </div>
          <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-emerald-100 text-emerald-800">
            Verified
          </span>
        </div>

        <div class="flex justify-between items-center pt-2">
          <div>
            <h4 class="text-sm font-medium text-gray-900">Notifications</h4>
            <p class="text-xs text-gray-500">Manage alerts</p>
          </div>
          <button class="text-indigo-600 text-sm font-medium hover:text-indigo-800 bg-indigo-50 px-3 py-1 rounded-md">Edit</button>
        </div>
      </div>

      <div class="mt-8 pt-6 border-t border-gray-100">
         <button @click="logout" class="w-full flex justify-center py-2 px-4 border border-red-300 rounded-md shadow-sm text-sm font-medium text-red-700 bg-white hover:bg-red-50 transition-colors">
          Sign Out
        </button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { useAuthStore } from '../stores/auth'
import { useRouter } from 'vue-router'

const authStore = useAuthStore()
const router = useRouter()

const logout = async () => {
  await authStore.logout()
  router.push('/login')
}
</script>

// frontend/src/pages/Profile.tsx
import { useNavigate, Link } from 'react-router-dom'
import { useAuthStore } from '@/stores/auth'

export default function Profile() {
  const user = useAuthStore((s) => s.user)
  const clear = useAuthStore((s) => s.clear)
  const navigate = useNavigate()

  function signOut() {
    clear()
    navigate('/login', { replace: true })
  }

  return (
    <div className="px-4 pt-4">
      <h1 className="text-xl">Profile</h1>

      <div className="card mt-4 flex items-center gap-4">
        <span className="flex h-16 w-16 items-center justify-center rounded-full bg-primary text-2xl font-bold text-white">
          {user?.name?.[0]?.toUpperCase() ?? '?'}
        </span>
        <div>
          <h2 className="text-lg">{user?.name}</h2>
          <p className="text-sm text-slate-500">{user?.email}</p>
          <span className="chip mt-1 bg-indigo-50 text-primary capitalize">{user?.role}</span>
        </div>
      </div>

      <div className="card mt-4 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <span className="text-2xl">🏅</span>
          <div>
            <p className="text-sm font-bold text-slate-800">Neighborhood Points</p>
            <p className="text-xs text-slate-500">Earn by saving places, reviewing &amp; posting</p>
          </div>
        </div>
        <p className="text-2xl font-extrabold text-accent">{user?.points ?? 0}</p>
      </div>

      <div className="card mt-4 space-y-1">
        <p className="text-sm font-bold text-slate-700">How to earn points</p>
        <ul className="list-inside list-disc space-y-1 text-xs text-slate-500">
          <li>Save a business → +2 points</li>
          <li>Write a review → +5 points</li>
          <li>Post in the feed → +1 point</li>
        </ul>
      </div>
      <div className="mt-6 space-y-2">
        {user?.role === 'admin' && (
          <Link
            to="/authority"
            className="btn-outline border-red-200 hover:bg-red-50/20 flex items-center justify-between w-full text-left text-sm font-semibold p-3 text-red-700"
          >
            <span>🚨 Civic Authority Portal (Admin)</span>
            <span className="text-red-400">→</span>
          </Link>
        )}
      </div>

      <button onClick={signOut} className="btn-danger mt-6 w-full">
        Sign Out
      </button>
    </div>
  )
}
